services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-backend
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/todoapp
    depends_on:
      - mongo
  mongo:
    image: mongo:5
    container_name: todo-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
