version: "3.9"

services:
  backend:
    build: .
    container_name: todo-backend
    ports:
      - "4000:4000"
    env_file: .env
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:5
    container_name: todo-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
